import '../core/models/checklist_model.dart';
import '../core/models/checklist_question_model.dart';

class SeedLoader {
  static List<Checklist> getInitialChecklists() {
return [
// ۱. چک‌لیست فایرباکس
Checklist(
id: 'hse_6_022',
code: 'HSE-6-022',
title: 'چک‌لیست بازرسی فایرباکس',
category: 'ایمنی و آتش‌نشانی',
description: 'بازرسی دوره‌ای جعبه‌های آتش‌نشانی',
questions: const [
ChecklistQuestion(id: 'fb_1', text: 'شیشه جعبه آتش‌نشانی سالم است؟', answerType: 'yes_no', order: 1),
ChecklistQuestion(id: 'fb_2', text: 'درب جعبه به‌راحتی باز و بسته می‌شود؟', answerType: 'yes_no', order: 2),
ChecklistQuestion(id: 'fb_3', text: 'شیلنگ برزنتی یا هوزریلی سالم و فاقد پارگی است؟', answerType: 'yes_no', order: 3),
ChecklistQuestion(id: 'fb_4', text: 'نازل متصل و سالم است؟', answerType: 'yes_no', order: 4),
ChecklistQuestion(id: 'fb_5', text: 'شیر فلکه اصلی آب روان و فاقد نشتی است؟', answerType: 'yes_no', order: 5),
ChecklistQuestion(id: 'fb_6', text: 'شیلنگ به‌درستی قرقره شده است؟', answerType: 'yes_no', order: 6),
ChecklistQuestion(id: 'fb_7', text: 'فشار آب مناسب است؟', answerType: 'yes_no', order: 7),
ChecklistQuestion(id: 'fb_8', text: 'جعبه تمیز و فاقد زنگ‌زدگی شدید است؟', answerType: 'yes_no', order: 8),
ChecklistQuestion(id: 'fb_9', text: 'مسیر دسترسی به فایرباکس باز است؟', answerType: 'yes_no', order: 9),id: 'prod_7', text: 'تهویه سالن به‌درستی عمل می‌کند؟', answerType: 'yes_no_partial', order: 7),
ChecklistQuestion(id: 'prod_8', text: 'چیدمان مواد اولیه و ضایعات منظم است؟', answerType: 'yes_no_partial', order: 8),
ChecklistQuestion(id: 'prod_9', text: 'کپسول‌های آتش‌نشانی در دسترس هستند؟', answerType: 'yes_no_partial', order: 9),
ChecklistQuestion(id: 'prod_10', text: 'پالت‌ها ایمن و پایدار چیده شده‌اند؟', answerType: 'yes_no_partial', order: 10),
ChecklistQuestion(id: 'prod_11', text: 'سطل‌های زباله به‌موقع تخلیه می‌شوند؟', answerType: 'yes_no_partial', order: 11),
ChecklistQuestion(id: 'prod_12', text: 'علائم هشداردهنده در محل‌های پرخطر نصب است؟', answerType: 'yes_no_partial', order: 12),
ChecklistQuestion(id: 'prod_13', text: 'تابلوهای برق بسته و ایمن هستند؟', answerType: 'yes_no_partial', order: 13),
ChecklistQuestion(id: 'prod_14', text: 'خروجی‌های اضطراری باز و مشخص هستند؟', answerType: 'yes_no_partial', order: 14),
ChecklistQuestion(id: 'prod_15', text: 'دوش و چشم‌شوی اضطراری آماده‌به‌کار است؟', answerType: 'yes_no_partial', order: 15),
ChecklistQuestion(id: 'prod_16', text: 'جعبه کمک‌های اولیه شارژ است؟', answerType: 'yes_no_partial', order: 16),
ChecklistQuestion(id: 'prod_17', text: 'نشتی روغن یا باد مشاهده نمی‌شود؟', answerType: 'yes_no_partial', order: 17),
ChecklistQuestion(id: 'prod_18', text: 'شرایط ارگونومی ایستگاه‌های کاری مناسب است؟', answerType: 'yes_no_partial', order: 18),
ChecklistQuestion(id: 'prod_19', text: 'میکروسوئیچ‌های ایمنی فعال هستند؟', answerType: 'yes_no_partial', order: 19),
ChecklistQuestion(id: 'prod_20', text: 'دستورالعمل ایمنی دستگاه‌ها نصب است؟', answerType: 'yes_no_partial', order: 20),
ChecklistQuestion(id: 'prod_21', text: 'کابل‌های برق روی زمین محافظ دارند؟', answerType: 'yes_no_partial', order: 21),
ChecklistQuestion(id: 'prod_22', text: 'نظافت و آراستگی محیط مطلوب است؟', answerType: 'yes_no_partial', order: 22),
ChecklistQuestion(id: 'prod_23', text: 'ضایعات قابل اشتعال روزانه خارج می‌شوند؟', answerType: 'yes_no_partial', order: 23),
ChecklistQuestion(id: 'prod_24', text: 'فضای آزاد مقابل تابلوهای برق رعایت شده است؟', answerType: 'yes_no_partial', order: 24),
ChecklistQuestion(id: 'prod_25', text: 'کاشف‌های حریق سقف سالن سالم هستند؟', answerType: 'yes_no_partial', order: 25),
ChecklistQuestion(id: 'prod_26', text: 'جرثقیل‌ها و بالابرها سالم هستند؟', answerType: 'yes_no_partial', order: 26),
ChecklistQuestion(id: 'prod_27', text: 'محل پارک ترولی‌ها ایمن است؟', answerType: 'yes_no_partial', order: 27),
ChecklistQuestion(id: 'prod_28', text: 'کارگران آموزش‌های ایمنی را گذرانده‌اند؟', answerType: 'yes_no_partial', order: 28),
],
),

// ۳. بازرسی ادواری انبارها
Checklist(
id: 'hse_6_027_wh',
code: 'HSE-6-027-2',
title: 'بازرسی ادواری انبارها',
category: 'بازرسی عمومی و ادواری',
description: 'کنترل ایمنی، چیدمان و حریق در انبارها',
questions: const [
ChecklistQuestion(id: 'wh_1', text: 'چیدمان اجناس بر اساس اصول ایمنی است؟', answerType: 'yes_no_partial', order: 1),
ChecklistQuestion(id: 'wh_2', text: 'فاصله کالاها تا سقف رعایت شده است؟', answerType: 'yes_no_partial', order: 2),
ChecklistQuestion(id: 'wh_3', text: 'راهروهای انبار عاری از مانع هستند؟', answerType: 'yes_no_partial', order: 3),
ChecklistQuestion(id: 'wh_4', text: 'برگه‌های MSDS در دسترس هستند؟', answerType: 'yes_no_partial', order: 4),
ChecklistQuestion(id: 'wh_5', text: 'مواد ناسازگار جداگانه نگهداری می‌شوند؟', answerType: 'yes_no_partial', order: 5),
ChecklistQuestion(id: 'wh_6', text: 'روشنایی راهروهای انبار کافی است؟', answerType: 'yes_no_partial', order: 6),
ChecklistQuestion(id: 'wh_7', text: 'تجهیزات اطفای حریق دسترسی آزاد دارند؟', answerType: 'yes_no_partial', order: 7),
ChecklistQuestion(id: 'wh_8', text: 'سیستم ارتینگ و صاعقه‌گیر سالم است؟', answerType: 'yes_no_partial', order: 8),
ChecklistQuestion(id: 'wh_9', text: 'پالت‌ها سالم و چینش کالاها پایدار است؟', answerType: 'yes_no_partial', order: 9),
ChecklistQuestion(id: 'wh_10', text: 'تابلوهای ممنوعیت استعمال دخانیات نصب است؟', answerType: 'yes_no_partial', order: 10),
ChecklistQuestion(id: 'wh_11', text: 'تهویه و کنترل دما و رطوبت فعال است؟', answerType: 'yes_no_partial', order: 11),
ChecklistQuestion(id: 'wh_12', text: 'خروجی‌های اضطراری بدون قفل هستند؟', answerType: 'yes_no_partial', order: 12),
ChecklistQuestion(id: 'wh_13', text: 'ضربه‌گیر پایه قفسه‌ها سالم است؟', answerType: 'yes_no_partial', order: 13),
ChecklistQuestion(id: 'wh_14', text: 'نردبان‌های انبار سالم و استاندارد هستند؟', answerType: 'yes_no_partial', order: 14),
],
),

// ۴. بازرسی کارگاه جوشکاری و برشکاری
Checklist(
id: 'hse_6_027_weld',
code: 'HSE-6-027-3',
title: 'بازرسی کارگاه جوشکاری و برشکاری',
category: 'بازرسی عمومی و ادواری',
description: 'کنترل ایمنی فعالیت‌های گرم و جوشکاری',
questions: const [
ChecklistQuestion(id: 'weld_1', text: 'کپسول‌های اکسیژن و استیلن مهار شده‌اند؟', answerType: 'yes_no_partial', order: 1),
ChecklistQuestion(id: 'weld_2', text: 'کپسول‌های پر و خالی تفکیک شده‌اند؟', answerType: 'yes_no_partial', order: 2),
ChecklistQuestion(id: 'weld_3', text: 'شیلنگ‌های گاز فاقد نشتی هستند؟', answerType: 'yes_no_partial', order: 3),
ChecklistQuestion(id: 'weld_4', text: 'شیرهای یک‌طرفه نصب و سالم هستند؟', answerType: 'yes_no_partial', order: 4),
ChecklistQuestion(id: 'weld_5', text: 'کابل‌های جوشکاری سالم هستند؟', answerType: 'yes_no_partial', order: 5),
ChecklistQuestion(id: 'weld_6', text: 'انبر جوش و اتصال زمین سالم هستند؟', answerType: 'yes_no_partial', order: 6),
ChecklistQuestion(id: 'weld_7', text: 'ماسک، دستکش و پیش‌بند استفاده می‌شود؟', answerType: 'yes_no_partial', order: 7),
ChecklistQuestion(id: 'weld_8', text: 'پرده ضدحریق نصب شده است؟', answerType: 'yes_no_partial', order: 8),
ChecklistQuestion(id: 'weld_9', text: 'کپسول اطفای حریق مناسب در دسترس است؟', answerType: 'yes_no_partial', order: 9),
ChecklistQuestion(id: 'weld_10', text: 'محیط کار فاقد مواد اشتعال‌پذیر است؟', answerType: 'yes_no_partial', order: 10),
ChecklistQuestion(id: 'weld_11', text: 'تهویه محل جوشکاری فعال است؟', answerType: 'yes_no_partial', order: 11),
ChecklistQuestion(id: 'weld_12', text: 'سنگ‌های فرز دارای حفاظ هستند؟', answerType: 'yes_no_partial', order: 12),
ChecklistQuestion(id: 'weld_13', text: 'پروانه کار گرم صادر شده است؟', answerType: 'yes_no_partial', order: 13),
ChecklistQuestion(id: 'weld_14', text: 'جعبه کمک‌های اولیه موجود است؟', answerType: 'yes_no_partial', order: 14),
],
),

// ۵. بازرسی تأسیسات و موتورخانه
Checklist(
id: 'hse_6_027_util',
code: 'HSE-6-027-4',
title: 'بازرسی تأسیسات و موتورخانه',
category: 'بازرسی عمومی و ادواری',
description: 'کنترل ایمنی تأسیسات و تجهیزات تحت فشار',
questions: const [
ChecklistQuestion(id: 'util_1', text: 'گیج‌های فشار و دما سالم هستند؟', answerType: 'yes_no_partial', order: 1),
ChecklistQuestion(id: 'util_2', text: 'شیرهای اطمینان تست دوره‌ای شده‌اند؟', answerType: 'yes_no_partial', order: 2),
ChecklistQuestion(id: 'util_3', text: 'پمپ‌ها و الکتروموتورها نشتی ندارند؟', answerType: 'yes_no_partial', order: 3),
ChecklistQuestion(id: 'util_4', text: 'تسمه‌ها و کوپلینگ‌ها حفاظ دارند؟', answerType: 'yes_no_partial', order: 4),
ChecklistQuestion(id: 'util_5', text: 'لوله‌کشی‌ها رنگ‌آمیزی و نام‌گذاری شده‌اند؟', answerType: 'yes_no_partial', order: 5),
ChecklistQuestion(id: 'util_6', text: 'کف موتورخانه فاقد روغن و آب است؟', answerType: 'yes_no_partial', order: 6),
ChecklistQuestion(id: 'util_7', text: 'روشنایی موتورخانه کافی است؟', answerType: 'yes_no_partial', order: 7),
ChecklistQuestion(id: 'util_8', text: 'تهویه موتورخانه فعال است؟', answerType: 'yes_no_partial', order: 8),
ChecklistQuestion(id: 'util_9', text: 'سنسورهای نشت گاز یا مبرد فعال هستند؟', answerType: 'yes_no_partial', order: 9),
ChecklistQuestion(id: 'util_10', text: 'تجهیزات نجات اضطراری موجود هستند؟', answerType: 'yes_no_partial', order: 10),
ChecklistQuestion(id: 'util_11', text: 'عایق لوله‌های بخار سالم است؟', answerType: 'yes_no_partial', order: 11),
ChecklistQuestion(id: 'util_12', text: 'اعلام و اطفای حریق فعال است؟', answerType: 'yes_no_partial', order: 12),
ChecklistQuestion(id: 'util_13', text: 'مخازن تحت فشار گواهی معتبر دارند؟', answerType: 'yes_no_partial', order: 13),
ChecklistQuestion(id: 'util_14', text: 'پمپ‌های تخلیه فعال هستند؟', answerType: 'yes_no_partial', order: 14),
ChecklistQuestion(id: 'util_15', text: 'کلید قطع اضطراری نصب است؟', answerType: 'yes_no_partial', order: 15),
ChecklistQuestion(id: 'util_16', text: 'درب موتورخانه به سمت بیرون باز می‌شود؟', answerType: 'yes_no_partial', order: 16),
ChecklistQuestion(id: 'util_17', text: 'دستورالعمل شرایط اضطراری نصب است؟', answerType: 'yes_no_partial', order: 17),
ChecklistQuestion(id: 'util_18', text: 'اتصال زمین تجهیزات برقرار است؟', answerType: 'yes_no_partial', order: 18),
ChecklistQuestion(id: 'util_19', text: 'سطح آب بویلرها خوانا است؟', answerType: 'yes_no_partial', order: 19),
ChecklistQuestion(id: 'util_20', text: 'کمپرسورها دارای حفاظ و سرویس معتبر هستند؟', answerType: 'yes_no_partial', order: 20),
ChecklistQuestion(id: 'util_21', text: 'تجهیزات حفاظت فردی تأسیسات موجود است؟', answerType: 'yes_no_partial', order: 21),
],
),

// ۶. بازرسی بهداشت و ایمنی رستوران
Checklist(
id: 'hse_6_027_rest',
code: 'HSE-6-027-5',
title: 'بازرسی بهداشت و ایمنی رستوران',
category: 'بازرسی عمومی و ادواری',
description: 'کنترل بهداشت محیط و ایمنی آشپزخانه',
questions: const [
ChecklistQuestion(id: 'rest_1', text: 'پرسنل کارت بهداشت معتبر دارند؟', answerType: 'yes_no_partial', order: 1),
ChecklistQuestion(id: 'rest_2', text: 'لباس کار و تجهیزات بهداشتی تمیز هستند؟', answerType: 'yes_no_partial', order: 2),
ChecklistQuestion(id: 'rest_3', text: 'کف، دیوار و سقف آشپزخانه تمیز است؟', answerType: 'yes_no_partial', order: 3),
ChecklistQuestion(id: 'rest_4', text: 'هود صنعتی فعال و تمیز است؟', answerType: 'yes_no_partial', order: 4),
ChecklistQuestion(id: 'rest_5', text: 'دمای یخچال‌ها ثبت و مناسب است؟', answerType: 'yes_no_partial', order: 5),
ChecklistQuestion(id: 'rest_6', text: 'تخته‌ها و چاقوها تفکیک شده‌اند؟', answerType: 'yes_no_partial', order: 6),
ChecklistQuestion(id: 'rest_7', text: 'سنسور نشت گاز فعال است؟', answerType: 'yes_no_partial', order: 7),
ChecklistQuestion(id: 'rest_8', text: 'کپسول اطفای حریق مناسب در دسترس است؟', answerType: 'yes_no_partial', order: 8),
ChecklistQuestion(id: 'rest_9', text: 'پتوی ضدحریق نزدیک اجاق‌ها نصب است؟', answerType: 'yes_no_partial', order: 9),
ChecklistQuestion(id: 'rest_10', text: 'سطل‌های زباله درب‌دار هستند؟', answerType: 'yes_no_partial', order: 10),
ChecklistQuestion(id: 'rest_11', text: 'توری پنجره‌ها سالم است؟', answerType: 'yes_no_partial', order: 11),
ChecklistQuestion(id: 'rest_12', text: 'ظروف به‌صورت بهداشتی شسته می‌شوند؟', answerType: 'yes_no_partial', order: 12),
ChecklistQuestion(id: 'rest_13', text: 'آب گرم مصرفی پایدار است؟', answerType: 'yes_no_partial', order: 13),
ChecklistQuestion(id: 'rest_14', text: 'لامپ‌ها قاب محافظ دارند؟', answerType: 'yes_no_partial', order: 14),
ChecklistQuestion(id: 'rest_15', text: 'مواد شوینده جدا از غذا نگهداری می‌شوند؟', answerType: 'yes_no_partial', order: 15),
ChecklistQuestion(id: 'rest_16', text: 'حشره‌کش‌های برقی ایمن نصب شده‌اند؟', answerType: 'yes_no_partial', order: 16),
ChecklistQuestion(id: 'rest_17', text: 'کفشورها دارای توری و سیفون هستند؟', answerType: 'yes_no_partial', order: 17),
ChecklistQuestion(id: 'rest_18', text: 'جعبه کمک‌های اولیه شارژ است؟', answerType: 'yes_no_partial', order: 18),
],
),

// ۷. بازرسی ایمنی محوطه و فضاهای عمومی
Checklist(
id: 'hse_6_027_yard',
code: 'HSE-6-027-6',
title: 'بازرسی ایمنی محوطه و فضاهای عمومی',
category: 'بازرسی عمومی و ادواری',
description: 'کنترل ایمنی معابر، محوطه و روشنایی محیطی',
questions: const [
ChecklistQuestion(id: 'yard_1', text: 'روشنایی محوطه در شب کافی است؟', answerType: 'yes_no_partial', order: 1),
ChecklistQuestion(id: 'yard_2', text: 'تابلوهای راهنمایی و محدودیت سرعت نصب هستند؟', answerType: 'yes_no_partial', order: 2),
ChecklistQuestion(id: 'yard_3', text: 'سرعت‌گیرها مشخص و قابل رؤیت هستند؟', answerType: 'yes_no_partial', order: 3),
ChecklistQuestion(id: 'yard_4', text: 'مسیر تردد افراد از خودروها جدا است؟', answerType: 'yes_no_partial', order: 4),
ChecklistQuestion(id: 'yard_5', text: 'محل ضایعات منظم و ایمن است؟', answerType: 'yes_no_partial', order: 5),
ChecklistQuestion(id: 'yard_6', text: 'منهول‌ها و کانال‌ها درپوش سالم دارند؟', answerType: 'yes_no_partial', order: 6),
ChecklistQuestion(id: 'yard_7', text: 'هایدرانت‌های محوطه سالم هستند؟', answerType: 'yes_no_partial', order: 7),
ChecklistQuestion(id: 'yard_8', text: 'درب‌های اضطراری بدون انسداد هستند؟', answerType: 'yes_no_partial', order: 8),
],
),

// ۸. بازرسی ایمنی و فنی لیفتراک
Checklist(
id: 'hse_6_027_fork',
code: 'HSE-6-027-7',
title: 'بازرسی ایمنی و فنی لیفتراک',
category: 'بازرسی عمومی و ادواری',
description: 'کنترل سلامت فنی و ایمنی لیفتراک',
questions: const [
ChecklistQuestion(id: 'fork_1', text: 'راننده گواهینامه معتبر لیفتراک دارد؟', answerType: 'yes_no_partial', order: 1),
ChecklistQuestion(id: 'fork_2', text: 'ترمز پایی و دستی سالم هستند؟', answerType: 'yes_no_partial', order: 2),
ChecklistQuestion(id: 'fork_3', text: 'چراغ‌ها و چراغ گردان سالم هستند؟', answerType: 'yes_no_partial', order: 3),
ChecklistQuestion(id: 'fork_4', text: 'بوق هشدار و دنده عقب کار می‌کنند؟', answerType: 'yes_no_partial', order: 4),
ChecklistQuestion(id: 'fork_5', text: 'شاخک‌ها فاقد ترک و خوردگی هستند؟', answerType: 'yes_no_partial', order: 5),
ChecklistQuestion(id: 'fork_6', text: 'جک‌ها و زنجیر دکل نشتی ندارند؟', answerType: 'yes_no_partial', order: 6),
ChecklistQuestion(id: 'fork_7', text: 'حفاظ بالاسری سالم است؟', answerType: 'yes_no_partial', order: 7),
ChecklistQuestion(id: 'fork_8', text: 'کمربند ایمنی سالم است؟', answerType: 'yes_no_partial', order: 8),
ChecklistQuestion(id: 'fork_9', text: 'کپسول اطفای حریق لیفتراک معتبر است؟', answerType: 'yes_no_partial', order: 9),
ChecklistQuestion(id: 'fork_10', text: 'لاستیک‌ها سالم هستند؟', answerType: 'yes_no_partial', order: 10),
ChecklistQuestion(id: 'fork_11', text: 'آینه‌ها سالم و تنظیم هستند؟', answerType: 'yes_no_partial', order: 11),
],
),

// ۹. ایمنی برق عمومی و تجهیزات
Checklist(
id: 'hse_6_028_gen',
code: 'HSE-6-028-1',
title: 'ایمنی برق عمومی و تجهیزات',
category: 'ایمنی برق',
description: 'بازرسی سیستم‌های الکتریکی عمومی و ارتینگ',
questions: const [
ChecklistQuestion(id: 'elec_gen_1', text: 'سیم‌کشی‌ها داخل مسیر محافظت‌شده هستند؟', answerType: 'yes_no_partial_na', order: 1),
ChecklistQuestion(id: 'elec_gen_2', text: 'پریزها و کلیدها درپوش سالم دارند؟', answerType: 'yes_no_partial_na', order: 2),
ChecklistQuestion(id: 'elec_gen_3', text: 'سیستم ارتینگ برقرار است؟', answerType: 'yes_no_partial_na', order: 3),
ChecklistQuestion(id: 'elec_gen_4', text: 'مقاومت چاه ارت به‌صورت دوره‌ای اندازه‌گیری می‌شود؟', answerType: 'yes_no_partial_na', order: 4),
ChecklistQuestion(id: 'elec_gen_5', text: 'کلیدهای محافظ جان نصب و تست شده‌اند؟', answerType: 'yes_no_partial_na', order: 5),
ChecklistQuestion(id: 'elec_gen_6', text: 'اضافه‌بار و تقسیم بار نامتعادل وجود ندارد؟', answerType: 'yes_no_partial_na', order: 6),
ChecklistQuestion(id: 'elec_gen_7', text: 'سیم‌های سیار فاقد زدگی هستند؟', answerType: 'yes_no_partial_na', order: 7),
ChecklistQuestion(id: 'elec_gen_8', text: 'روشنایی اضطراری فعال است؟', answerType: 'yes_no_partial_na', order: 8),
ChecklistQuestion(id: 'elec_gen_9', text: 'علائم خطر برق‌گرفتگی نصب است؟', answerType: 'yes_no_partial_na', order: 9),
ChecklistQuestion(id: 'elec_gen_10', text: 'برق‌کاران تجهیزات حفاظت فردی عایق دارند؟', answerType: 'yes_no_partial_na', order: 10),
ChecklistQuestion(id: 'elec_gen_11', text: 'ترمینال‌ها فاقد داغ‌زدگی هستند؟', answerType: 'yes_no_partial_na', order: 11),
ChecklistQuestion(id: 'elec_gen_12', text: 'فیوزها متناسب با آمپراژ کابل انتخاب شده‌اند؟', answerType: 'yes_no_partial_na', order: 12),
ChecklistQuestion(id: 'elec_gen_13', text: 'جعبه تقسیم‌ها درب بسته دارند؟', answerType: 'yes_no_partial_na', order: 13),
ChecklistQuestion(id: 'elec_gen_14', text: 'کابل‌های عبوری از کف محافظ دارند؟', answerType: 'yes_no_partial_na', order: 14),
ChecklistQuestion(id: 'elec_gen_15', text: 'سیستم صاعقه‌گیر سالم است؟', answerType: 'yes_no_partial_na', order: 15),
ChecklistQuestion(id: 'elec_gen_16', text: 'تجهیزات برقی فاقد نشتی آب هستند؟', answerType: 'yes_no_partial_na', order: 16),
ChecklistQuestion(id: 'elec_gen_17', text: 'دستورالعمل برق‌گرفتگی نصب است؟', answerType: 'yes_no_partial_na', order: 17),
ChecklistQuestion(id: 'elec_gen_18', text: 'بازرسی ترموویژن انجام شده است؟', answerType: 'yes_no_partial_na', order: 18),
],
),

// ۱۰. بازرسی تابلوهای برق توزیع و قدرت
Checklist(
id: 'hse_6_028_panel',
code: 'HSE-6-028-2',
title: 'بازرسی تابلوهای برق توزیع و قدرت',
category: 'ایمنی برق',
description: 'کنترل تابلوهای برق، شینه‌ها و کلیدهای حفاظتی',
questions: const [
ChecklistQuestion(id: 'panel_1', text: 'درب تابلو قفل و دسترسی محدود است؟', answerType: 'yes_no_partial_na', order: 1),
ChecklistQuestion(id: 'panel_2', text: 'پوشش محافظ شینه‌ها نصب است؟', answerType: 'yes_no_partial_na', order: 2),
ChecklistQuestion(id: 'panel_3', text: 'فرش عایق جلوی تابلو سالم است؟', answerType: 'yes_no_partial_na', order: 3),
ChecklistQuestion(id: 'panel_4', text: 'نقشه تک‌خطی تابلو نصب است؟', answerType: 'yes_no_partial_na', order: 4),
ChecklistQuestion(id: 'panel_5', text: 'فضای دسترسی مقابل تابلو باز است؟', answerType: 'yes_no_partial_na', order: 5),
ChecklistQuestion(id: 'panel_6', text: 'بدنه تابلو به ارت متصل است؟', answerType: 'yes_no_partial_na', order: 6),
ChecklistQuestion(id: 'panel_7', text: 'چراغ‌های سیگنال سالم هستند؟', answerType: 'yes_no_partial_na', order: 7),
ChecklistQuestion(id: 'panel_8', text: 'گلند کابل‌ها محکم هستند؟', answerType: 'yes_no_partial_na', order: 8),
ChecklistQuestion(id: 'panel_9', text: 'فن و فیلتر تابلو فعال و تمیز هستند؟', answerType: 'yes_no_partial_na', order: 9),
ChecklistQuestion(id: 'panel_10', text: 'داخل تابلو فاقد گردوغبار و رطوبت است؟', answerType: 'yes_no_partial_na', order: 10),
ChecklistQuestion(id: 'panel_11', text: 'وسیله متفرقه داخل تابلو وجود ندارد؟', answerType: 'yes_no_partial_na', order: 11),
ChecklistQuestion(id: 'panel_12', text: 'سیستم LOTO برای کلید اصلی موجود است؟', answerType: 'yes_no_partial_na', order: 12),
ChecklistQuestion(id: 'panel_13', text: 'کپسول CO2 نزدیک تابلو موجود است؟', answerType: 'yes_no_partial_na', order: 13),
ChecklistQuestion(id: 'panel_14', text: 'سیم‌کشی داخل تابلو شماره‌گذاری شده است؟', answerType: 'yes_no_partial_na', order: 14),
ChecklistQuestion(id: 'panel_15', text: 'کلید اصلی روان و سالم است؟', answerType: 'yes_no_partial_na', order: 15),
ChecklistQuestion(id: 'panel_16', text: 'رله‌های حفاظتی فعال هستند؟', answerType: 'yes_no_partial_na', order: 16),
ChecklistQuestion(id: 'panel_17', text: 'علامت هشدار ولتاژ درج شده است؟', answerType: 'yes_no_partial_na', order: 17),
ChecklistQuestion(id: 'panel_18', text: 'قطعات برق‌دار بدون پوشش وجود ندارند؟', answerType: 'yes_no_partial_na', order: 18),
],
),

// ۱۱. بازرسی پست برق و ترانسفورماتورها
Checklist(
id: 'hse_6_028_sub',
code: 'HSE-6-028-3',
title: 'بازرسی پست برق و ترانسفورماتورها',
category: 'ایمنی برق',
description: 'کنترل ایمنی پست، ترانسفورماتورها و تجهیزات فشارقوی',
questions: const [
ChecklistQuestion(id: 'sub_1', text: 'درب پست قفل و ورود افراد متفرقه ممنوع است؟', answerType: 'yes_no_partial_na', order: 1),
ChecklistQuestion(id: 'sub_2', text: 'ترانس فاقد نشتی روغن و داغی غیرعادی است؟', answerType: 'yes_no_partial_na', order: 2),
ChecklistQuestion(id: 'sub_3', text: 'گیج روغن و ترمومتر ترانس سالم هستند؟', answerType: 'yes_no_partial_na', order: 3),
ChecklistQuestion(id: 'sub_4', text: 'حوضچه روغن‌گیر تمیز است؟', answerType: 'yes_no_partial_na', order: 4),
ChecklistQuestion(id: 'sub_5', text: 'میله عایق نجات موجود است؟', answerType: 'yes_no_partial_na', order: 5),
ChecklistQuestion(id: 'sub_6', text: 'دستکش و کفش عایق معتبر موجود است؟', answerType: 'yes_no_partial_na', order: 6),
ChecklistQuestion(id: 'sub_7', text: 'فازمتر فشارقوی سالم است؟', answerType: 'yes_no_partial_na', order: 7),
ChecklistQuestion(id: 'sub_8', text: 'اتصال زمین بدنه و نول مطمئن است؟', answerType: 'yes_no_partial_na', order: 8),
ChecklistQuestion(id: 'sub_9', text: 'دژنکتورها و سکسیونرها سرویس شده‌اند؟', answerType: 'yes_no_partial_na', order: 9),
ChecklistQuestion(id: 'sub_10', text: 'سیستم اعلام و اطفای حریق فعال است؟', answerType: 'yes_no_partial_na', order: 10),
ChecklistQuestion(id: 'sub_11', text: 'روشنایی اضطراری کافی است؟', answerType: 'yes_no_partial_na', order: 11),
ChecklistQuestion(id: 'sub_12', text: 'تهویه پست فعال است؟', answerType: 'yes_no_partial_na', order: 12),
ChecklistQuestion(id: 'sub_13', text: 'توری‌های محافظ نصب هستند؟', answerType: 'yes_no_partial_na', order: 13),
ChecklistQuestion(id: 'sub_14', text: 'رله‌های حفاظتی سالم هستند؟', answerType: 'yes_no_partial_na', order: 14),
ChecklistQuestion(id: 'sub_15', text: 'تابلوهای اخطار و دستورالعمل ورود نصب هستند؟', answerType: 'yes_no_partial_na', order: 15),
ChecklistQuestion(id: 'sub_16', text: 'باتری‌خانه و شارژر سالم هستند؟', answerType: 'yes_no_partial_na', order: 16),
],
),

// ۱۲. بازرسی ابزارها و وسایل برقی پرتابل
Checklist(
id: 'hse_6_028_port',
code: 'HSE-6-028-4',
title: 'بازرسی ابزارها و وسایل برقی پرتابل',
category: 'ایمنی برق',
description: 'کنترل ابزارهای برقی دستی و کابل‌های سیار',
questions: const [
ChecklistQuestion(id: 'port_1', text: 'بدنه ابزار فاقد شکستگی است؟', answerType: 'yes_no_partial_na', order: 1),
ChecklistQuestion(id: 'port_2', text: 'کابل ورودی فاقد زدگی و وصله است؟', answerType: 'yes_no_partial_na', order: 2),
ChecklistQuestion(id: 'port_3', text: 'دوشاخه سالم و دارای ارت است؟', answerType: 'yes_no_partial_na', order: 3),
ChecklistQuestion(id: 'port_4', text: 'محل ورود کابل محافظ مناسب دارد؟', answerType: 'yes_no_partial_na', order: 4),
ChecklistQuestion(id: 'port_5', text: 'کلید روشن و خاموش سالم است؟', answerType: 'yes_no_partial_na', order: 5),
ChecklistQuestion(id: 'port_6', text: 'حفاظ تیغه یا سنگ فرز سالم است؟', answerType: 'yes_no_partial_na', order: 6),
ChecklistQuestion(id: 'port_7', text: 'سرعت دیسک با دستگاه متناسب است؟', answerType: 'yes_no_partial_na', order: 7),
ChecklistQuestion(id: 'port_8', text: 'ابزار عایق دوبل یا سیم ارت مطمئن دارد؟', answerType: 'yes_no_partial_na', order: 8),
ChecklistQuestion(id: 'port_9', text: 'برچسب بازرسی دوره‌ای معتبر نصب است؟', answerType: 'yes_no_partial_na', order: 9),
ChecklistQuestion(id: 'port_10', text: 'قرقره کابل سیار محافظ اضافه‌بار دارد؟', answerType: 'yes_no_partial_na', order: 10),
ChecklistQuestion(id: 'port_11', text: 'کاربر از دستکش و عینک محافظ استفاده می‌کند؟', answerType: 'yes_no_partial_na', order: 11),
ChecklistQuestion(id: 'port_12', text: 'ابزار در محیط مرطوب بدون حفاظت استفاده نمی‌شود؟', answerType:_partial_na', order: 6),
ChecklistQuestion(id: 'port_7', text: 'سرعت دیسک با دستگاه متناسب است؟', answerType: 'yes_no_partial_na', order: 7),
ChecklistQuestion(id: 'port_8', text: 'ابزار عایق دوبل یا سیم ارت مطمئن دارد؟', answerType: 'yes_no_partial_na', o
