import '../core/models/checklist_model.dart';
import '../core/models/checklist_question_model.dart';

class SeedLoader {
  static List<Checklist> getInitialChecklists() {
    return [
      Checklist(
        id: 'hse_6_022',
        code: 'HSE-6-022',
        title: 'چک‌لیست بازرسی فایرباکس',
        category: 'ایمنی و آتش‌نشانی',
        description: 'بازرسی دوره‌ای جعبه‌های آتش‌نشانی (فایرباکس)',
        questions: const [
          ChecklistQuestion(id: 'fb_1', text: 'شیشه جعبه آتش‌نشانی سالم است؟', answerType: 'yes_no', order: 1),
          ChecklistQuestion(id: 'fb_2', text: 'درب جعبه به راحتی باز و بسته می‌شود و قفل نیست؟', answerType: 'yes_no', order: 2),
          ChecklistQuestion(id: 'fb_3', text: 'شیلنگ برزنتی یا هوزریلی سالم و فاقد پوسیدگی یا پارگی است؟', answerType: 'yes_no', order: 3),
          ChecklistQuestion(id: 'fb_4', text: 'نازل (سرلول) متصل، سالم و دارای اهرم کارکرد روان است؟', answerType: 'yes_no', order: 4),
          ChecklistQuestion(id: 'fb_5', text: 'شیر فلکه اصلی آب روان است و نشتی ندارد؟', answerType: 'yes_no', order: 5),
          ChecklistQuestion(id: 'fb_6', text: 'شیلنگ به درستی قرقره شده و آماده بهره‌برداری سریع است؟', answerType و آماده بهره‌برداری سریع است؟', answerType: 'yes_nofb_7', text: 'فشار آب مناسب و دارای گیج خوانا در صورت وجود است؟', answerType: 'yes_no', order: 7),
          ChecklistQuestion(id: 'fb_8', text: 'جعبه تمیز، فاقد گردوغبار شدید و زنگ‌زدگی است؟', answerType: 'yes_no', order: 8),
          ChecklistQuestion(id: 'fb_9', text: 'مسیر دسترسی به فایرباکس کاملاً باز و بدون مانع است؟', answerType: 'yes_no', order: 9),
          ChecklistQuestion(id: 'fb_10', text: 'شماره و پلاک شناسایی فایرباکس خوانا و الصاق شده است؟', answerType: 'yes_no', order: 10),
        ],
      ),
      Checklist(
        id: 'hse_6_027_prod',
        code: 'HSE-6-027-1',
        title: 'بازرسی ادواری سالن‌های تولید',
        category: 'بازرسی عمومی و ادواری',
        description: 'چک‌لیست کنترل شرایط ایمنی و بهداشت سالن‌های تولید',
        questions: const [
          ChecklistQuestion(id: 'p_1', text: 'کف سالن تمیز، فاقد لکه‌های روغن، گریس و آب لغزنده است؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'p_2', text: 'خط‌کشی راهروها، مسیرهای تردد و حریم دستگاه‌ها مشخص است؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'p_3', text: 'حفاظ‌های ایمنی قطعات دوار و خطرناک دستگاه‌ها نصب هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'p_4', text: 'کلیدهای توقف اضطراری سالم و دردسترس هستند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'p_5', text: 'کارگران از تجهیزات حفاظت فردی استفاده می‌کنند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'p_6', text: 'روشنایی عمومی و موضعی ایستگاه‌های کاری کافی است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'p_7', text: 'سیستم‌های تهویه عمومی و موضعی سالن به‌درستی عمل می‌کنند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'p_8', text: 'چیدمان مواد اولیه و ضایعات منظم و خارج از مسیر تردد است؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'p_9', text: 'کپسول‌های اطفای حریق دسترسی آزاد و کارت بازرسی دارند؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'p_10', text: 'پالت‌ها و استاک‌ها با ارتفاع استاندارد و ایمن چیده شده‌اند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'p_11', text: 'سطل‌های زباله تفکیک‌شده و مخازن ضایعات مرتب تخلیه می‌شوند؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'p_12', text: 'علائم هشداردهنده و ایمنی در محل‌های پرخطر نصب شده است؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'p_13', text: 'تابلوهای برق سالن بسته و بدون سیم‌کشی لخت هستند؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'p_14', text: 'خروجی‌های اضطراری باز، روشن و دارای تابلو خروج هستند؟', answerType: 'yes_no_partial', order: 14),
          ChecklistQuestion(id: 'p_15', text: 'دوش و چشم‌شوی اضطراری در صورت نیاز آماده‌به‌کار است؟', answerType: 'yes_no_partial', order: 15),
          ChecklistQuestion(id: 'p_16', text: 'جعبه کمک‌های اولیه سالن شارژ و در دسترس است؟', answerType: 'yes_no_partial', order: 16),
          ChecklistQuestion(id: 'p_17', text: 'نشتی روغن یا باد در اتصالات مشاهده نمی‌شود؟', answerType: 'yes_no_partial', order: 17),
          ChecklistQuestion(id: 'p_18', text: 'وضعیت ارگونومی اپراتورها و میزهای کار استاندارد است؟', answerType: 'yes_no_partial', order: 18),
          ChecklistQuestion(id: 'p_19', text: 'میکروسوئیچ‌های ایمنی فعال و پل نشده‌اند؟', answerType: 'yes_no_partial', order: 19),
          ChecklistQuestion(id: 'p_20', text: 'دستورالعمل‌های ایمنی کار با دستگاه‌ها نصب است؟', answerType: 'yes_no_partial', order: 20),
          ChecklistQuestion(id: 'p_21', text: 'سیم‌کشی‌ها و کابل‌های برق روی زمین ایمن هستند؟', answerType: 'yes_no_partial', order: 21),
          ChecklistQuestion(id: 'p_22', text: 'وضعیت نظافت و آراستگی محیط در حد مطلوب است؟', answerType: 'yes_no_partial', order: 22),
          ChecklistQuestion(id: 'p_23', text: 'ضایعات نساجی و قابل اشتعال روزانه از سالن خارج می‌شوند؟', answerType: 'yes_no_partial', order: 23),
          ChecklistQuestion(id: 'p_24', text: 'حداقل یک متر فضای آزاد مقابل تابلوهای برق رعایت شده است؟', answerType: 'yes_no_partial', order: 24),
          ChecklistQuestion(id: 'p_25', text: 'سنسورها و کاشف‌های حریق سقف سالن سالم و تمیز هستند؟', answerType: 'yes_no_partial', order: 25),
          ChecklistQuestion(id: 'p_26', text: 'جرثقیل‌ها و بالابرها قلاب ضامندار و ترمز سالم دارند؟', answerType: 'yes_no_partial', order: 26),
          ChecklistQuestion(id: 'p_27', text: 'محل پارک گاری‌ها و ترولی‌ها خارج از مسیرهای اصلی است؟', answerType: 'yes_no_partial', order: 27),
          ChecklistQuestion(id: 'p_28', text: 'کارگران آموزش‌های ایمنی اولیه و اطفای حریق را گذرانده‌اند؟', answerType: 'yes_no_partial', order: 28),
        ],
      ),
      Checklist(
        id: 'hse_6_027_wh',
        code: 'HSE-6-027-2',
        title: 'بازرسی ادواری انبارها',
        category: 'بازرسی عمومی و ادواری',
        description: 'چک‌لیست ایمنی، چیدمان و حریق در انبارها',
        questions: const [
          ChecklistQuestion(id: 'wh_1', text: 'قفسه‌بندی‌ها: 'قفسه‌بندی‌ها یا دیوار هستند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'wh_2', text: 'فاصله کالاها تا سقف و تجهیزات اعلام و اطفا رعایت شده است؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'wh_3', text: 'راهروهای تردد لیفتراک و افراد مشخص و عاری از مانع هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'wh_4', text: 'برگه‌های اطلاعات ایمنی مواد شیمیایی MSDS در دسترس است؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'wh_5', text: 'مواد ناسازگار و قابل اشتعال در مکان‌های مجزا نگهداری می‌شوند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'wh_6', text: 'روشنایی عمومی راهروهای انبار کافی است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id:(id: 'wh_7', text: 'تجهیزطفای حریق انبار بازدیدشده و دارای دسترسی آزاد هستند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'wh_8', text: 'سیستم ارتینگ و صاعقه‌گیر انبار سالم و متصل است؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'wh_9', text: 'پالت‌ها سالم و چینش کالاها پایدار و ایمن است؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'wh_10', text: 'تابلوهای «استعمال دخانیات اکیداً ممنوع» نصب شده است؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'wh_11', text: 'سیستم تهویه و کنترل دما و رطوبت فعال است؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'wh_12', text: 'درب‌های خروج اضطراری در شیفت کاری بدون قفل هستند؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'wh_13', text: 'حفاظ و ضربه‌گیر پایه‌های قفسه‌ها نصب و سالم هستند؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'wh_14', text: 'نردبان‌ها و تجهیزات دسترسی انبار استاندارد و سالم هستند؟', answerType: 'yes_no_partial', order: 14),
        ],
      ),
      Checklist(
        id: 'hse_6_027_weld',
        code: 'HSE-6-027-3',
        title: 'بازرسی کارگاه جوشکاری و برشکاری',
        category: 'بازرسی عمومی و ادواری',
        description: 'ایمنی فرایندهای گرم، جوشکاری برق و اکسی‌استیلن',
        questions: const [
          ChecklistQuestion(id: 'w_1', text: 'کپسول‌های گاز اکسیژن و استیلن دارای کلاهک و مهار هستند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'w_2', text: 'کپسول‌های گاز پر و خالی از یکدیگر تفکیک شده‌اند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'w_3', text: 'شیلنگ‌های گاز فاقد نشتی و پوسیدگی هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'w_4', text: 'شیرهای یکطرفه Flashback Arrestor نصب هستند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'w_5', text: 'کابل‌های جوشکاری برق سالم و دارای عایق کامل هستند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'w_6', text: 'انبر جوش و گیره اتصال به زمین استاندارد و سالم هستند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'w_7', text: 'ماسک جوشکاری، دستکش چرمی و پیش‌بند استفاده می‌شود؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'w_8', text: 'پارتیشن یا پرده ضدحریق برای حفاظت سایرین نصب است؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'w_9', text: 'کپسول آتش‌نشانی مناسب در فاصله حداکثر پنج متری است؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'w_10', text: 'محیط جوشکاری تا شعاع حداقل ده متر فاقد مواد اشتعال‌پذیر است؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'w_11', text: '', answerType: 'yes_no_partial جوشکاری فعال است؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'w_12', text: 'سنگ‌های فرز دارای حفاظ کامل و مهره استاندارد هستند؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'w_13', text: 'پروانه کار گرم برای نقاط پرخطر صادر شده است؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'w_14', text: 'جعبه کمک‌های اولیه و شستشوی چشم موجود است؟', answerType: 'yes_no_partial', order: 14),
        ],
      ),
      Checklist(
        id: 'hse_6_027_util',
        code: 'HSE-6-027-4',
        title: 'بازرسی تأسیسات و موتورخانه',
        category: 'بازرسی عمومی و ادواری',
        description: 'ایمنی بویلرها، چیلرها، کمپرسورها، پمپ‌ها و مخازن تحت فشار',
        questions: const [
          ChecklistQuestion(id: 'u_1', text: 'گیج‌های فشار و دماسنج‌های دیگ‌ها و مخازن سالم هستند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'u_2', text: 'شیرهای اطمینان بازرسی و تست دوره‌ای شده‌اند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'u_3', text: 'پمپ‌ها و الکتروموتورها فاقد لرزش، صدای غیرعادی و نشتی هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'u_4', text: 'تسمه و کوپلینگ تجهیزات دوار دارای حفاظ مناسب هستند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'u_5', text: 'لوله‌کشی‌ها بر اساس استاندارد رنگ‌آمیزی و نام‌گذاری شده‌اند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'u_6', text: 'کف موتورخانه عاری از روغن، آب و نشتی مایعات است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'u_7', text: 'روشنایی عمومی و اضطراری موتورخانه کافی است؟', answerType: 'yes_no_partial',ستم تهویه دائم و ه ChecklistQuestion(id: 'u_8', text: 'سیستم تهویه دائم و هواکش‌های تخلیه گاز فعال هستند؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'u_9', text: 'سنسورهای نشت گاز یا مبرد در محل‌های لازم فعال هستند؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'u_10', text: 'ماسک‌های تنفسی و تجهیزات نجات اضطراری موجود هستند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'u_11', text: 'عایق‌کاری حرارتی لوله‌های بخار و آب گرم سالم است؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'u_12', text: 'سیستم اعلام و اطفای حریق موتورخانه فعال است؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'u_13', text: 'مخازن تحت فشار دارای پلاک فنی و گواهی بازرسی هستند؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'u_14', text: 'چاهک‌های تخلیه و پمپ‌های لجن‌کش فعال هستند؟', answerType: 'yes_no_partial', order: 14),
          ChecklistQuestion(id: 'u_15', text: 'کلید قطع اضطراری اصلی موتورخانه نصب است؟', answerType: 'yes_no_partial', order: 15),
          ChecklistQuestion(id: 'u_16', text: 'درب‌های موتورخانه به سمت بیرون باز می‌شوند؟', answerType: 'yes_no_partial', order: 16),
          ChecklistQuestion(id: 'u_17', text: 'دستورالعمل شرایط اضطراری در ورودی موتورخانه نصب است؟', answerType: 'yes_no_partial', order: 17),
          ChecklistQuestion(id: 'u_18', text: 'اتصال زمین تجهیزات و بدنه پمپ‌ها برقرار است؟', answerType: 'yes_no_partial', order: 18),
          ChecklistQuestion(id: 'u_19', text: 'سطح تراز آب بویلرها شفاف، تمیز و خوانا است؟', answerType: 'yes_no_partial', order: 19),
          ChecklistQuestion(id: 'u_20', text: 'کمپرسورهای', order: 20),
          ChecklistQuestion(id هستند؟', answerType: 'yes_no_partial', order: 20),
          ChecklistQuestion(id: 'u_21', text: 'تجهیزات حفاظت فردی ویژه تأسیسات موجود است؟', answerType: 'yes_no_partial', order: 21),
        ],
      ),
      Checklist(
        id: 'hse_6_027_rest',
        code: 'HSE-6-027-5',
        title: 'بازرسی بهداشت و ایمنی رستوران',
        category: 'بازرسی عمومی و ادواری',
        description: 'ارزیابی بهداشت محیط، ایمنی گاز و سلامت پرسنل آشپزخانه',
        questions: const [
          ChecklistQuestion(id: 'r_1', text: 'پرسنل آشپزخانه کارت بهداشت معتبر دارند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'r_2', text: 'لباس کار، کلاه، دستکش و پیش‌بند تمیز استفاده می‌شود؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'r_3', text: 'کف، دیوارها و سقف آشپزخانه تمیز و شستشو داده شده است؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'r_4', text: 'هود صنعتی فعال و فاقد چربی انباشته است؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'r_5', text: 'دمای یخچال‌ها و سردخانه‌ها استاندارد و ثبت می‌شود؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'r_6', text: 'مواد غذایی با تخته‌ها و چاقوهای تفکیک‌شده آماده می‌شوند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'r_7', text: 'شیرهای قطع خودکار و سنسورهای نشت گاز فعال هستند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'r_8', text: ': 'کپسولطفای حریق مناسب آشپزخانه در دسترس هستند؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'r_9', text: 'پتوی ضدحریق نزدیک اجاق‌ها نصب و آماده است؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'r_10', text: 'سطل‌های زباله درب پدالی و تخلیه به‌موقع دارند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'r_11', text: 'توری پنجره‌ها برای جلوگیری از ورود حشرات سالم است؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'r_12', text: 'ظروف با آب گرم و ماده ضدعفونی شسته می‌شوند؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'r_13', text: 'سیستم آب گرم مصرفی پایدار و بهداشتی است؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'r_14', text: 'لامپ‌ها دارای قاب محافظ نشکن هستند؟', answerType: 'yes_no_partial', order: 14),
          ChecklistQuestion(id: 'r_15', text: 'مواد شوینده جدا از محل مواد غذایی نگهداری می‌شوند؟', answerType: 'yes_no_partial', order: 15),
          ChecklistQuestion(id: 'r_16', text: 'حشره‌کش‌های برقی خارج از حریم مستقیم غذا نصب هستند؟', answerType: 'yes_no_partial', order: 16),
          ChecklistQuestion(id: 'r_17', text: 'کفشورها دارای توری، سیفون و فاقد بوی نامطبوع هستند؟', answerType: 'yes_no_partial', order: 17),
          ChecklistQuestion(id: 'r_18', text: 'جعبه کمک‌های اولیه سوختگی و بریدگی شارژ است؟', answerType: 'yes_no_partial', order: 18),
        ],
      ),
      Checklist(
        id: 'hse_6_027_yard',
        code: 'HSE-6-027-6',
        title: 'بازرسی ایمنی محوطه و فضاهای عمومی',
        category: 'بازرسی عمومی و ادواری',
        description: 'ایمنی معابر، سرعت‌گیرها، روشنایی و فضای سبز کارخانه',
ایی و فضای سبز کارخانه',
        questions: const [
          Checklist', text: 'روشنایی معابر و محوطه بیرونی در شب کافی است؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'yd_2', text: 'تابلوهای راهنمایی و حداکثر سرعت نصب هستند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'yd_3', text: 'سرعت‌گیرها رنگ‌آمیزی و دارای بازتابش مناسب هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'yd_4', text: 'مسیر تردد افراد سالم و از تردد خودروها تفکیک شده است؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'yd_5', text: 'محل دپوی ضایعات منظم و فاقد خطر گسترش آتش‌سوزی است؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'yd_6', text: 'منهول‌ها و کانال‌های آب دارای درپوش محکم هستند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'yd_7', text: 'هایدرانت‌های محوطه سالم و آماده‌به‌کار هستند؟', answerType: 'yes_no_partialرب order: 7),
          ChecklistQuestion(id: 'yd_8', text: 'درب‌های اضطراری کارخانه باز و بدون انسداد هستند؟', answerType: 'yes_no_partial', order: 8),
        ],
      ),
      Checklist(
        id: 'hse_6_027_fork',
        code: 'HSE-6-027-7',
        title: 'بازرسی ایمنی و فنی لیفتراک',
        category: 'بازرسی عمومی و ادواری',
        description: 'کنترل سلامت فنی و ایمنی لیفتراک‌ها',
        questions: const [
          ChecklistQuestion(id: 'fk_1', text: 'راننده دارای گواهینامه ویژه لیفتراک است؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'fk_2', text: 'ترمز پایی و دستی کاملاً سالم هستند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'fk_3', text: 'چراغ‌ها و چراغ گردان سالم هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'fk_4', text: 'بوق هشدار و بوق دنده عقب درست کار می‌کنند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'fk_5', text: 'شyes_no_partial',قد تابیدگی، ترک و خوردگی هستند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'fk_6', text: 'جک‌های هیدرولیک و زنجیر دکل بدون نشتی و آسیب هستند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'fk_7', text: 'حفاظ بالاسری راننده محکم و استاندارد است؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'fk_8', text: 'کمربند ایمنی موجود و سالم است؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'fk_9', text: 'کپسول اطفای حریق لیفتراک شارژ معتبر دارد؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'fk_10', text: 'لاستیک‌ها سالم و دارای عاج مناسب هستند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'fk_11', text: 'آینه‌ها سالم و تنظیم شده‌اند؟', answerType: 'yes_no_partial', orderType: 'yes_no_partial', order: 11),
        ],
      ),
     _6_028_gen',
        code: 'HSE-6-028-1',
        title: 'ایمنی برق عمومی و تجهیزات',
        category: 'ایمنی برق',
        description: 'بازرسی سیستم‌های الکتریکی عمومی، ارتینگ و کلیدها',
        questions: const [
          ChecklistQuestion(id: 'e_gen_1', text: 'سیم‌کشی‌ها داخل لوله، خرطومی استاندارد یا داکت هستند؟', answerType: 'yes_no_partial_na', order: 1),
          ChecklistQuestion(id: 'e_gen_2', text: 'پریزها و کلیدها دارای درپوش سالم هستند؟', answerType: 'yes_no_partial_na', order: 2),
          ChecklistQuestion(id: 'e_gen_3', text: 'سیستم ارتینگ سراسری برقرار است؟', answerType: 'yes_no_partial_na', order: 3),
          ChecklistQuestion(id: 'e_gen_4', text: 'مقاومت چاه ارت دوره‌ای اندازه‌گیری و کمتر از پنج اهم است؟', answerType: 'yes_no_partial_na', order: 4),
          ChecklistQuestion(id: 'e_gen_5', text: 'کلیدهای محافظ جان نصب و تست شده‌اند؟', answerType: 'yes_no_partial_na', order: 5),
          ChecklistQuestion(id: 'e_gen_6', text: 'اضافه‌بار و تقسیم بار نامتعادل وجود ندارد؟', answerType: 'yes_no_partial_na', order: 6),
          ChecklistQuestion(id: 'e_gen_7', text: 'سیم‌های سیار استاندارد و بدون زدگی هستند؟', answerType: 'yes_no_partial_na', order: 7),
          ChecklistQuestion(id: 'e_gen_8', text: 'روشنایی اضطراری هنگام قطعی برق فعال می‌شود؟', answerType: 'yes_no_partial_na', order: 8),
          ChecklistQuestion(id: 'e_gen_9', text: 'علائم خطر برق‌گرفتگی نصب شده است؟', answerType: 'yes_no_partial_na', order: 9),
          ChecklistQuestion(id: 'e_gen_10', text: 'برق‌کاران تجهیزات حفاظت فردی عایق دارند؟', answerType: 'yes_no_partial_na', order: 10),
          ChecklistQuestion(id: 'e_gen_11', text: 'ترمینال‌ها و اتصالات فاقد داغ‌زدگی هستند؟', answerType: 'yes_no_partial_na', order: 11),
          ChecklistQuestion(id: 'e_gen_12', text: 'فیوزها_naناسب با آمپراژ کابل انتخاب شده‌اند؟', answerType: 'yes_no_partial_na', order: 12),
          ChecklistQuestion(id: 'e_gen_13', text: 'جعبه تقسیم‌ها درب بسته و عایق مناسب دارند؟', answerType: 'yes_no_partial_na', order: 13),
          ChecklistQuestion(id: 'e_gen_14', text: 'کابل‌های عبوری از کف محافظ دارند؟', answerType: 'yes_no_partial_na', order: 14),
          ChecklistQuestion(id: 'e_gen_15', text: 'سیستم صاعقه‌گیر تست و سالم است؟', answerType: 'yes_no_partial_na', order: 15),
          ChecklistQuestion(id: 'e_gen_16', text: 'تجهیزات برقی فاقد نشتی آب هستند؟', answerType: 'yes_no_partial_na', order: 16),
          ChecklistQuestion(id: 'e_gen_17', text: 'دستورالعمل برق‌گرفتگی در اتاق برق نصب است؟', answerType: 'yes_no_partial_na', order: 17),
          ChecklistQuestion(id: 'e_gen_18', text: 'بازرسی ترموویژن اتصالات انجام شده است؟', answerType: 'yes_no_partial_na', order: 18),
        ],
      ),
      Checklist(
        id: 'hse_6_028_panel',
        code: 'HSE-6-028-2',
        title: 'بازرسی تابلوهای برق توزیع و قدرت',
        category: 'ایمنی برق',
        description: 'کنترل تابلوهای برق، شینه‌ها، کلیدها و قفل ایمنی',
        questions: const [
          ChecklistQuestion(id: 'pnl_1', text: 'درب تابلوها قفل و کلید در اختیار فرد مجاز است؟', answerType: 'yes_no_partial_na', order: 1),
          ChecklistQuestion(id: 'pnl_2', text: 'پوشش محافظ روی شینه‌های برق‌دار نصب است؟', answerType: 'yes_no_partial_na', order: 2),
          ChecklistQuestion(id: 'pnl_3', text: 'فرش عایق مناسب جلوی تابلو پهن است؟', answerType: 'yes_no_partial_na', order: 3),
          ChecklistQuestion(id: 'pnl_4', text: 'نقشه تک‌خطی و راهنمای کلیدها نصب است؟', answerType: 'yes_no_partial_na', order: 4),
          ChecklistQuestion(id: 'pnl_5', text: 'حریم دسترسی مقابل تابلو باز است؟', answerType: 'yes_no_partial_na', order: 5),
          ChecklistQuestion(id: 'pnl_6', text: 'بدنه و درب تابلو به ارت متصل هستند؟', answerType: 'yes_no_partial_na', order: 6),
          ChecklistQuestion(id: 'pnl_7', text: 'چراغ‌های سیگنال و نمایشگرها سالم هستند؟', answerType: 'yes_no_partial_na', order: 7),
          ChecklistQuestion(id: 'pnl_8', text: 'گلند کابل‌ها محکم و بدون درز باز هستند؟', answerType: 'yes_no_partial_na', order: 8),
          ChecklistQuestion(id: 'pnl_9', text: 'فن و فیلترهای تابلو تمیز و فعال هستند؟', answerType: 'yes_no_partial_na', order: 9),
          ChecklistQuestion(id: 'pnl_10', text: 'داخل تابلو فاقد گردوغبار و رطوبت است؟', answerType: 'yes_no_partial_na', order: 10),
          ChecklistQuestion(id: 'pnl_11', text: 'وسیله متفرقه داخل تابلو نگهداری نمی‌شود؟', answerType:', answerType: 'yes_no_partial_na', order: 11(id: 'pnl_12', text: 'سیستم LOTO برای کلیدهای اصلی موجود است؟', answerType: 'yes_no_partial_na', order: 12),
          ChecklistQuestion(id: 'pnl_13', text: 'کپسول CO2 مناسب نزدیک تابلو نصب است؟', answerType: 'yes_no_partial_na', order: 13),
          ChecklistQuestion(id: 'pnl_14', text: 'سیم‌کشی داخل تابلو شماره‌گذاری شده است؟', answerType: 'yes_no_partial_na', order: 14),
          ChecklistQuestion(id: 'pnl_15', text: 'کلید اصلی قطع بار روان و بدون گیر است؟', answerType: 'yes_no_partial_na', order: 15),
          ChecklistQuestion(id: 'pnl_16', text: 'رله‌های حفاظتی و کنترل فاز فعال هستند؟', answerType: 'yes_no_partial_na', order: 16),
          ChecklistQuestion(id: 'pnl_17', text: 'علامت هشدار ولتاژ روی تابلو درج است؟', answerType: 'yes_no_partial_na', order: 17),
          ChecklistQuestion(id: 'pnl_18', text: 'قطعه کلید مینیاتوری بدون قاب وجود ندارد؟', answerType: 'yes_no_partial_na', order: 18),
        ],
      ),
      Checklist(
        id: 'hse_6_028_sub',
        code: 'HSE-6-028-3',
        title: 'بازرسی پست برق و ترانسفورماتورها',
        category: 'ایمنی برق',
        description: 'ایمنی ولتاژ متوسط و بالا، ترانس‌ها و دژنکتورها',
        questions: const [
          ChecklistQuestion(id: 'sub_1', text: 'درب پست برق قفل و ورود افراد متفرقه ممنوع است؟', answerType: 'yes_no_partial_na', order: 1),
          ChecklistQuestion(id: 'sub_2', text: 'ترانسفورماتور فاقد نشتی روغن و داغی بیش از حد است؟', answerType: 'yes_no_partial_na', order: 2),
          ChecklistQuestion(id: 'sub_3', text: 'گیج روغن، رطوبت‌گیر و ترمومتر ترانس سالم هستند؟', answerType: 'yes_no_partial_na', order: 3),
          ChecklistQuestion(id: 'sub_4', text: 'حوضچه روغن‌گیر زیر ترانس تمیز است؟', answerType: 'yes_no_partial_na', order: 4),
          ChecklistQuestion(id: 'sub_5', text: 'اهرم و میله عایق نجات پرسنل در پست موجود است؟', answerType: 'yes_no_partial_na', order: 5),
          ChecklistQuestion(id: 'sub_6', text: 'دستکش و کفش عایق فشار قوی با تاریخ آزمون معتبر موجود است؟', answerType: 'yes_no_partial_na', order: 6),
          ChecklistQuestion(id: 'sub_7', text: 'فازمتر فشار قوی سالم و آماده‌به‌کار است؟', answerType: 'yes_no_partial_na', order: 7),
          ChecklistQuestion(id: 'sub_8', text: 'اتصال زمین بدنه و نول ترانس مطمئن است؟', answerType: 'yes_no_partial_na', order: 8),
          ChecklistQuestion(id: 'sub_9', text: 'دژنکتورها و سکسیونرها تست و سرویس شده‌اند؟', answerType: 'yes_no_partial_na', order: 9),
          ChecklistQuestion(id: 'sub_10', text: 'سیستم اعلام و اطفای حریق اتوماتیک فعال است؟', answerType: 'yes_no_partial_na', order: 10),
          ChecklistQuestion(id: 'sub_11', text: 'روشنایی اضطراری اتاق ترانس کافی است؟', answerType: 'yes_no_partial_na', order: 11),
          ChecklistQuestion(id: 'sub_12', text: 'تهویه دائم پست برق فعال است؟', answerType: 'yes_no_partial_na', order: 12),
          ChecklistQuestion(id: 'sub_13', text: 'توری‌های محافظ پنجره‌ها نصب است؟', answerType: 'yes_no_partial_na', order: 13),
          ChecklistQuestion(id: 'sub_14', text: 'رله‌های حفاظتی و ترموستات ترانس سالم هستند؟', answerType: 'yes_no_partial_na', order: 14),
          ChecklistQuestion(id: 'sub_15', text: 'تابلوهای اخطار ولتاژ و دستورالعمل ورود نصب شده‌اند؟', answerType: 'yes_no_partial_na', order: 15),
          ChecklistQuestion(id: 'sub_16', text: 'باطری‌خانه و شارژر باطری‌ها سالم هستند؟', answerType: 'yes_no_partial_na', order: 16),
        ],
      ),
      Checklist(
        id: 'hse_6_028_port',
        code: 'HSE-6-028-4',
        title: 'بازرسی ابزارها و وسایل برقی پرتابل',
        category: 'ایمنی برق',
        description: 'ایمنی دریل، سنگ فرز، کابل سیار و ابزارهای برقی',
        questions: const [
          ChecklistQuestion(id: 'prt_1', text: 'بدنه ابزار برقی فاقد شکستگی و نقص است؟', answerType: 'yes_no_partial_na', order: 1),
          ChecklistQuestion(id: 'prt_2', text: 'کابل ورودی فاقد زدگی، بریدگی و وصالی است؟', answerType: 'yes_no_partial_na', order: 2),
          ChecklistQuestion(id: 'prt_3', text: 'دوشاخه سالم و دارای ارت است؟', answerType: 'yes_no_partial_na', order: 3),
          ChecklistQuestion(id: 'prt_4', text: 'محل ورود کابل دارای محافظ مناسب است؟', answerType: 'yes_no_partial_na', order: 4),
          ChecklistQuestion(id: 'prt_5', text: 'کلید روشن و خاموش سالم و روان است؟', answerType: 'yes_no_partial_na', order: 5),
          ChecklistQuestion(id: 'prt_6', text: 'حفاظ تیغه، دیسک یا سنگ فرز محکم است؟', answerکم است؟', answerType: 'yes_no_partial_na', order: 6),
 'prt_7', text: 'سرعت مجاز دیسک با دستگاه متناسب است؟', answerType: 'yes_no_partial_na', order: 7),
          ChecklistQuestion(id: 'prt_8', text: 'ابزار دارای عایق دوبل یا سیم ارت مطمئن است؟', answerType: 'yes_no_partial_na', order: 8),
          ChecklistQuestionزرسی دوره‌ای معتبر روی ابزار نصب است؟',چسب بازرسی دوره‌ای معتبر روی ابزار نصب است؟', answerType: 'yes_no_partial_na', order: 9),
          ChecklistQuestion(id: 'prt_10', text: 'قرقره کابل سیار دارای محافظ اضافه‌بار است؟', answerType: 'yes_no_partial_na', order: 10),
          ChecklistQuestion(id: 'prt_11', text: 'کاربر از دستکش عایق و عینک محافظ استفاده می‌کند؟', answerType: 'yes_no_partial_na', order: 11),
          ChecklistQuestion(id: 'prt_12', text: 'ابزار در محیط مرطوب بدون محافظ استفاده نمی‌شود؟', answerType: 'yes_no_partial_na', order: 12),
          ChecklistQuestion(id: 'prt_13', text: 'ابزار معیوب با برچسب خارج از سرویس تفکیک شده است؟', answerType: 'yes_no_partial_na', order: 13),
          ChecklistQuestion(id: 'prt_14', text: 'آچار مخصوص تعویض تیغه یا سنگ موجود است؟', answerType: 'yes_no_partial_na', order: 14),
          ChecklistQuestion(id: 'prt_15', text: 'پریزهای ابزار پرتابل مجهز به محافظ جان هستند؟', answerType: 'yes_no_partial_na', order: 15),
          ChecklistQuestion(id: 'prt_16', text: 'ابزارها پس از کار در محل مخصوص نگهداری می‌شوند؟', answerType: 'yes_no_partial_na', order: 16),
        ],
      ),
    ];
  }
}
