import '../core/models/checklist_model.dart';
import '../core/models/checklist_question_model.dart';

class SeedLoader {
  static List<Checklist> getInitialChecklists() {
    return [
      // 1. HSE-6-022 - فایرباکس
      Checklist(
        id: 'hse_6_022',
        code: 'HSE-6-022',
        title: 'چک‌لیست بازرسی فایرباکس',
        category: 'ایمنی و آتش‌نشانی',
        description: 'بازرسی دوره‌ای جعبه‌های آتش‌نشانی (فایرباکس)',
        questions: const [
          ChecklistQuestion(id: 'fb_1', text: 'شیشه جعبه آتش‌نشانی سالم است؟', answerType: 'yes_no', order: 1),
          ChecklistQuestion(id: 'fb_2', text: 'درب جعبه به راحتی باز و بسته می‌شود و قفل نیست؟', answerType: 'yes_no', order: 2),
          ChecklistQuestion(id: 'fb_3', text: 'شیلنگ برزنتی یا هوزریلی سالم و فاقد پوسیدگی یا پارگی است؟', answerType: 'yes_no', order: 3),
          ChecklistQuestion(id: 'fb_4', text: 'نازل (سرلول) متصل، سالم و دارای اهرم کارکرد روان است؟', answerType: 'yes_no', order: 4),
          ChecklistQuestion(id: 'fb_5', text: 'شیر فلکه اصلی آب روان است و نشتی ندارد؟', answerType: 'yes_no', order: 5),
          ChecklistQuestion(id: 'fb_6', text: 'شیلنگ به درستی قرقره شده و آماده بهره‌برداری سریع است؟', answerType: 'yes_no', order: 6),
          ChecklistQuestion(id: 'fb_7', text: 'فشار آب مناسب و دارای گیج خوانا در صورت وجود است؟', answerType: 'yes_no', order: 7),
          ChecklistQuestion(id: 'fb_8', text: 'جعبه تمیز، فاقد گردوغبار شدید و زنگ‌زدگی است؟', answerType: 'yes_no', order: 8),
          ChecklistQuestion(id: 'fb_9', text: 'مسیر دسترسی به فایرباکس کاملاً باز و بدون مانع است؟', answerType: 'yes_no', order: 9),
          ChecklistQuestion(id: 'fb_10', text: 'شماره و پلاک شناسایی فایرباکس خوانا و الصاق شده است؟', answerType: 'yes_no', order: 10),
        ],
      ),

      // 2. HSE-6-027 - سالن تولید
      Checklist(
        id: 'hse_6_027_prod',
        code: 'HSE-6-027-1',
        title: 'بازرسی ادواری سالن‌های تولید',
        category: 'بازرسی عمومی و ادواری',
        description: 'چک‌لیست کنترل و ارزیابی شرایط ایمنی و بهداشت سالن‌های تولید',
        questions: const [
          ChecklistQuestion(id: 'p_1', text: 'کف سالن تمیز، فاقد لکه‌های روغن، گریس و آب لغزنده است؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'p_2', text: 'خط‌کشی راهروها، مسیرهای تردد و حریم دستگاه‌ها مشخص است؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'p_3', text: 'حفاظ‌های ایمنی قطعات دوار و خطرناک دستگاه‌ها نصب هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'p_4', text: 'کلیدهای توقف اضطراری (Emergency Stop) سالم و دردسترس هستند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'p_5', text: 'کارگران از تجهیزات حفاظت فردی (کفش، گوشی، دستکش و...) استفاده می‌کنند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'p_6', text: 'روشنایی عمومی و موضعی ایستگاه‌های کاری کافی و مناسب است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'p_7', text: 'سیستم‌های تهویه عمومی و موضعی سالن به درستی عمل می‌کنند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'p_8', text: 'چیدمان مواد اولیه و ضایعات منظم و خارج از مسیر تردد است؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'p_9', text: 'کپسول‌های اطفای حریق سالن دارای دسترسی آزاد و کارت بازرسی هستند؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'p_10', text: 'پالت‌ها و استاک‌ها با ارتفاع استاندارد و ایمن چیده شده‌اند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'p_11', text: 'سطل‌های زباله تفکیک‌شده و مخازن ضایعات تمیز تخلیه می‌شوند؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'p_12', text: 'علائم هشداردهنده و ایمنی در محل‌های پرخطر نصب شده است؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'p_13', text: 'تابلوهای برق سالن بسته، دارای کلید و بدون سیم‌کشی لخت هستند؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'p_14', text: 'خروجی‌های اضطراری باز، روشن و دارای تابلو خروج هستند؟', answerType: 'yes_no_partial', order: 14),
          ChecklistQuestion(id: 'p_15', text: 'دوش و چشم‌شوی اضطراری (در صورت وجود مواد شیمیایی) آماده بکار است؟', answerType: 'yes_no_partial', order: 15),
          ChecklistQuestion(id: 'p_16', text: 'جعبه کمک‌های اولیه سالن شارژ، تمیز و در دسترس است؟', answerType: 'yes_no_partial', order: 16),
          ChecklistQuestion(id: 'p_17', text: 'نشتی روغن یا باد در اتصالات لوله‌ها و دستگاه‌ها مشاهده نمی‌شود؟', answerType: 'yes_no_partial', order: 17),
          ChecklistQuestion(id: 'p_18', text: 'وضعیت ارگونومی اپراتورها و صندلی‌ها/میزهای کار استاندارد است؟', answerType: 'yes_no_partial', order: 18),
          ChecklistQuestion(id: 'p_19', text: 'میکروسوئیچ‌های ایمنی درب‌ها و حفاظ‌ها فعال و پل نشده‌اند؟', answerType: 'yes_no_partial', order: 19),
          ChecklistQuestion(id: 'p_20', text: 'دستورالعمل‌های ایمنی کار با دستگاه‌ها روی آن‌ها نصب است؟', answerType: 'yes_no_partial', order: 20),
          ChecklistQuestion(id: 'p_21', text: 'وضعیت سیم‌کشی‌ها و کابل‌های برق روی زمین استاندارد و ایمن است؟', answerType: 'yes_no_partial', order: 21),
          ChecklistQuestion(id: 'p_22', text: 'وضعیت نظافت و آراستگی محیط (5S) در حد مطلوب است؟', answerType: 'yes_no_partial', order: 22),
          ChecklistQuestion(id: 'p_23', text: 'ضایعات نساجی و قابل اشتعال به صورت روزانه از سالن خارج می‌شوند؟', answerType: 'yes_no_partial', order: 23),
          ChecklistQuestion(id: 'p_24', text: 'دسترسی به تابلوهای برق اصلی با حداقل ۱ متر فاصله آزاد است؟', answerType: 'yes_no_partial', order: 24),
          ChecklistQuestion(id: 'p_25', text: 'سنسورها و کاشف‌های حریق سقف سالن سالم و تمیز هستند؟', answerType: 'yes_no_partial', order: 25),
          ChecklistQuestion(id: 'p_26', text: 'جرثقیل‌های سقفی و بالابرهای سالن دارای قلاب ضامندار و ترمز سالمند؟', answerType: 'yes_no_partial', order: 26),
          ChecklistQuestion(id: 'p_27', text: 'محل پارک گاری‌ها و ترولی‌ها خارج از مسیرهای اصلی است؟', answerType: 'yes_no_partial', order: 27),
          ChecklistQuestion(id: 'p_28', text: 'کارگران آموزش‌های ایمنی اولیه و اطفای حریق را گذرانده‌اند؟', answerType: 'yes_no_partial', order: 28),
        ],
      ),

      // 3. HSE-6-027 - انبارها
      Checklist(
        id: 'hse_6_027_wh',
        code: 'HSE-6-027-2',
        title: 'بازرسی ادواری انبارها',
        category: 'بازرسی عمومی و ادواری',
        description: 'چک‌لیست ایمنی، چیدمان و حریق در انبارهای مواد و محصول',
        questions: const [
          ChecklistQuestion(id: 'wh_1', text: 'قفسه‌بندی‌ها محکم، فاقد خمیدگی و مهارشده به کف یا دیوار هستند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'wh_2', text: 'فاصله کالاها تا سقف و تجهیزات اعلام/اطفا (حداقل ۹۰ سانتی‌متر) رعایت شده؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'wh_3', text: 'راهروهای تردد لیفتراک و افراد مشخص و عاری از هرگونه مانع است؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'wh_4', text: 'برگه‌های اطلاعات ایمنی مواد شیمیایی (MSDS) در دسترس است؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'wh_5', text: 'مواد ناسازگار و قابل اشتعال در مکان‌های مجزا نگهداری می‌شوند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'wh_6', text: 'روشنایی عمومی راهروهای انبار کافی و بدون لامپ سوخته است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'wh_7', text: 'تجهیزات اطفای حریق انبار کافی، بازدیدشده و دسترسی آزاد دارند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'wh_8', text: 'سیستم ارتینگ و صاعق (حداقل ۹۰ سانتی‌متر) رعایت شده؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'wh_3', text: 'راهروهای تردد لیفتراک و افراد مشخص و عاری از هرگونه مانع است؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'wh_4', text: 'برگه‌های اطلاعات ایمنی مواد شیمیایی (MSDS) در دسترس است؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'wh_5', text: 'مواد ناسازگار و قابل اشتعال در مکان‌های مجزا نگهداری می‌شوند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'wh_6', text: 'روشنایی عمومی راهروهای انبار کافی و بدون لامپ سوخته است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'wh_7', text: 'تجهیزات اطفای حریق انبار کافی، بازدیدشده و دسترسی آزاد دارند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'wh_8', text: 'سیستم ارتینگ و صاعقه‌گیر انبار سالم و متصل است؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'wh_9', text: 'پالت‌ها سالم و چینش کالاها روی آن‌ها پایدار و فاقد خطر سقوط است؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'wh_10', text: 'تابلوهای اخطاری «استعمال دخانیات اکیداً ممنوع» نصب شده است؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'wh و اکسی‌استیلن',
        questions: const [
          ChecklistQuestion(id: 'w_1', text: 'کپسول‌های گاز اکسیژن و استیلن دارای کلاهک، مهار و زنجیر هستند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'w_2', text: 'کپسول‌های گاز پر و خالی از یکدیگر تفکیک شده‌اند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'w_3', text: 'شیلنگ‌های گاز فاقد نشتی، پوسیدگی و بست نامناسب هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'w_4', text: 'شیرهای یکطرفه (Flashback Arrestor) روی مشعل و رگولاتور نصب هستند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'w_5', text: 'کابل‌های جوشکاری برق سالم، دارای عایق کامل و فاقد وصالی لخت هستند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'w_6', text: 'انبر جوش و گیره اتصال به زمین (اتصال بدنه) استاندارد و سالمند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'w_7', text: 'ماسک جوشکاری، دستکش چرمی ساق‌بلند، پیش‌بند و گت استفاده می‌شود؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'w_8', text: 'پارتیشن یا پرده‌های ضد حریق برای حفاظت سایرین از اشعه نصب است؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'w_9', text: 'کپسول آتش‌نشانی پودری یا CO2 در فاصله حداکثر ۵ متری محل جوشکاری است؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'w_10', text: 'محیط جوشکاری فاقد مواد اشتعال‌پذیر تا شعاع حداقل ۱۰ متری است؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'w_11', text: 'سیستم مکنده و تهویه موضعی دود جوشکاری فعال است؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'w_12', text: 'سنگ‌های فرز دارای حفاظ کامل، مهره استاندارد و آچار مخصوصند؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'w_13', text: 'پروانه کار گرم (Hot Work Permit) برای نقاط پرخطر صادر شده است؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'w_14', text: 'جعبه کمک‌های اولیه و قطره شستشوی چشم در کارگاه موجود است؟', answerType: 'yes_no_partial', order: 14),
        ],
      ),

      // 5. HSE-6-027 - تاسیسات و موتورخانه
      Checklist(
        id: 'hse_6_027_util',
        code: 'HSE-6-027-4',
        title: 'بازرسی تاسیسات و موتورخانه',
        category: 'بازرسی عمومی و ادواری',
        description: 'ایمنی بویلرها، چیلرها، کمپرسورها، پمپ‌ها و مخازن تحت فشار',
        questions: const [
          ChecklistQuestion(id: 'u_1', text: 'گیج‌های فشار و دماسنج‌های دیگ‌ها و مخازن سالم و کالیبره هستند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'u_2', text: 'شیرهای اطمینان (Safety Valve) بازرسی و تست دوره‌ای شده‌اند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'u_3', text: 'پمپ‌ها و الکتروموتورها فاقد لرزش، صدای غیرعادی و نشتی هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'u_4', text: 'تسمه و کوپلینگ تمام تجهیزات دوار دارای حفاظ مناسب فلزی هستند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'u_5', text: 'مسیر لوله‌کشی‌ها بر اساس استاندارد رنگ‌آمیزی و نام‌گذاری شده‌اند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'u_6', text: 'کف موتورخانه عاری از روغن، آب و نشتی مایعات است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'u_7', text: 'روشنایی عمومی و روشنایی اضطراری موتورخانه کافی است؟', answerType: 'yes_no__4', text: 'تسمه و کوپلینگ تمام تجهیزات دوار دارای حفاظ مناسب فلزی هستند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'u_5', text: 'مسیر لوله‌کشی‌ها بر اساس استاندارد رنگ‌آمیزی و نام‌گذاری شده‌اند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'u_6', text: 'کف موتورخانه عاری از روغن، آب و نشتی مایعات است؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'u_7', text: 'روشنایی عمومی و روشنایی اضطراری موتورخانه کافی است؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'u_8', text: 'سیستم تهویه دائم و هواکش‌های تخلیه گاز فعال هستند؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'u_9', text: 'کپسول‌های گاز کلر یا مبردهای آمونیاک/فریون دارای سنسور نشتی هستند؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'u_10', text: 'ماسک‌های تنفسی و تجهیزات نجات اضطراری خارج از موتورخانه نصبند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'u_11', text: 'عایق‌کاری حرارتی لوله‌های بخار و آب گرم سالم و کامل است؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'u_12', text: 'سیستم اعلام و اطفای حریق موتورخانه فعال و آماده بکار است؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'u_13', text: 'مخازن تحت فشار دارای پلاک مشخصات فنی و گواهی بازرسی هستند؟', answerType: 'yes_no_partial', order:_17', text: 'دستورالعمل شرایط اضطراری در ورودی موتورخانه نصب است؟', answerType: 'yes_no_partial', order: 17),
          ChecklistQuestion(id: 'u_18', text: 'سیستم اتصال زمین (ارت) تجهیزات و بدنه پمپ‌ها متصل است؟', answerType: 'yes_no_partial', order: 18),
          ChecklistQuestion(id: 'u_19', text: 'سطح تراز آب بویلرها و آب‌نماها شفاف، تمیز و خوانا است؟', answerType: 'yes_no_partial', order: 19),
          ChecklistQuestion(id: 'u_20', text: 'کمپرسورهای هوا دارای تخلیه خودکار آب کندانس هستند؟', answerType: 'yes_no_partial', order: 20),
          ChecklistQuestion(id: 'u_21', text: 'تجهیزات حفاظت فردی ویژه تاسیسات در محل موجود است؟', answerType: 'yes_no_partial', order: 21),
        ],
      ),

      // 6. HSE-6-027 - رستوران و آشپزخانه
      Checklist(
        id: 'hse_6_027_rest',
        code: 'HSE-6-027-5',
        title: 'بازرسی بهداشت و ایمنی رستوران',
        category: 'بازرسی عمومی و ادواری',
        description: 'ارزیابی بهداشت محیط، ایمنی گاز و سلامت پرسنل آشپزخانه',
        questions: const [
          ChecklistQuestion(id: 'r_1', text: 'پرسنل آشپزخانه دارای کارت بهداشت معتبر و گواهی سلامت هستند؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'r_2', text: 'لباس کار، کلاه، دستکش و پیش‌بند تمیز توسط پرسنل استفاده می‌شود؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'r_3', text: 'کف، دیوارها و سقف سالن غذاخوری و آشپزخانه تمیز و شستشوداده‌شده است؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'r_4', text: 'سیستم هود صنعتی و مکنده‌های آشپزخانه فعال و فاقد چربی انباشته است؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'r_5', text: 'دمای یخچال‌ها و سردخانه‌های نگهداری مواد غذایی استاندارد و ثبت می‌شود؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'r_6', text: 'گوشت، مرغ و سبزیجات در تخته‌ها و چاقوهای تفکیک‌شده آماده‌سازی می‌شوند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'r_7', text: 'شیرهای قطع خودکار گاز و سنسورهای نشت گاز در آشپزخانه فعالند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'r_8', text: 'کپسول‌های اطفای حریق CO2 و فوم مناسب آشپزخانه در دسترس هستند؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'r_9', text: 'پتوی ضد حریق (Fire Blanket) در نزدیکی اجاق‌ها نصب و آماده است؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'r_10', text: 'سطل‌های زباله دارای درب پدالی، کیسه زباله و تخلیه به موقع هستند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'r_11', text: 'توری پنجره‌ها برای جلوگیری از ورود حشرات سالم و نصب است؟', answerType: 'yes_no_partial', order: 11),
          ChecklistQuestion(id: 'r_12', text: 'ظروف، قاشق و چنگال‌ها با آب گرم و مایع ضدعفونی شسته می‌شوند؟', answerType: 'yes_no_partial', order: 12),
          ChecklistQuestion(id: 'r_13', text: 'سیستم آب گرم مصرفی پایدار و بهداشتی است؟', answerType: 'yes_no_partial', order: 13),
          ChecklistQuestion(id: 'r_14', text: 'روشنایی سالن و آشپزخانه دارای قاب محافظ نشکن روی لامپ‌ها است؟', answerType: 'yes_no_partial', order: 14),
          ChecklistQuestion(id: 'r_15', text: 'مواد شوینده و شیمیایی کاملاً جدا از محل نگهداری مواد غذایی است؟', answerType: 'yes_no_partial', order: 15),
          ChecklistQuestion(id: 'r_16', text: 'حشره‌کش‌های برقی در محل‌های مناسب و خارج از حریم مستقیم غذا نصبند؟', answerType: 'yes_no_partial', order: 16),
          ChecklistQuestion(id: 'r_17', text: 'کفشورها دارای توری فلزی، سیفون و فاقد بوی نامطبوع هستند؟', answerType: 'yes_no_partial', order: 17),
          ChecklistQuestion(id: 'r_18', text: 'جعبه کمک‌های اولیه مخصوص سوختگی و بریدگی شارژ است؟', answerType: 'yes_no_partial', order: 18),
        ],
      ),

      // 7. HSE-6-027 - محوطه و فضاهای باز
      Checklist(
        id: 'hse_6_027_yard',
        code: 'HSE-6-027-6',
        title: 'بازرسی ایمنی محوطه و فضاهای عمومی',
        category: 'بازرسی عمومی و ادواری',
        description: 'ایمنی معابر، سرعت‌گیرها، روشنایی و فضای سبز کارخانه',
        questions: const [
          ChecklistQuestion(id: 'yd_1', text: 'روشنایی معابر، خیابان‌ها و محوطه بیرونی در شب کافی است؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'yd_2', text: 'تابلوهای راهنمایی، رانندگی و حداکثر سرعت در معابر نصب هستند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'yd_3', text: 'سرعت‌گیرها رنگ‌آمیزی شده و دارای بازتابش مناسب هستند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'yd_4', text: 'پیاده‌روها و مسیر تردد افراد سالم و تفکیک‌شده از تردد خودروهاست؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'yd_5', text: 'محل دپوی ضایعات محوطه منظم و فاقد خطر گسترش آتش‌سوزی است؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'yd_6', text: 'منهول‌ها، کانال‌های آب و چاه‌های محوطه دارای درپوش محکم و ایمن هستند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'yd_7', text: 'هایدرانت‌ها (شیرهای ایستاده آتش‌نشانی) محوطه سالم و آماده بکارند؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'yd_8', text: 'درب‌های ورود/خروج اضطراری کارخانه باز و فاقد هرگونه انسداد هستند؟', answerType: 'yes_no_partial', order: 8),
        ],
      ),

      // 8. HSE-6-027 - لیفتراک و وسایل نقلیه صنعتی
      Checklist(
        id: 'hse_6_027_fork',
        code: 'HSE-6-027-7',
        title: 'بازرسی ایمنی و فنی لیفتراک',
        category: 'بازرسی عمومی و ادواری',
        description: 'چک‌لیست کنترل روزانه/دوره‌ای سلامت فنی و ایمنی لیفتراک‌ها',
        questions: const [
          ChecklistQuestion(id: 'fk_1', text: 'راننده دارای گواهینامه ویژه رانندگی با لیفتراک است؟', answerType: 'yes_no_partial', order: 1),
          ChecklistQuestion(id: 'fk_2', text: 'ترمز پایی و ترمز دستی لیفتراک کاملاً سالم و قوی عمل می‌کنند؟', answerType: 'yes_no_partial', order: 2),
          ChecklistQuestion(id: 'fk_3', text: 'چراغ‌های جلو، عقب، خطر و چراغ گردان چشمک‌زن سالمند؟', answerType: 'yes_no_partial', order: 3),
          ChecklistQuestion(id: 'fk_4', text: 'بوق هشدار و بوق دنده عقب خودکار به درستی کار می‌کنند؟', answerType: 'yes_no_partial', order: 4),
          ChecklistQuestion(id: 'fk_5', text: 'شاخک‌ها (Forks) فاقد تابیدگی، ترک، جوشکاری غیراصولی و خوردگی هستند؟', answerType: 'yes_no_partial', order: 5),
          ChecklistQuestion(id: 'fk_6', text: 'جک‌های بالابر هیدرولیک و زنجیر دکل بدون نشتی و آسیب هستند؟', answerType: 'yes_no_partial', order: 6),
          ChecklistQuestion(id: 'fk_7', text: 'حفاظ بالاسری راننده (Overhead Guard) محکم و استاندارد است؟', answerType: 'yes_no_partial', order: 7),
          ChecklistQuestion(id: 'fk_8', text: 'کمربند ایمنی راننده موجود، سالم و حین رانندگی استفاده می‌شود؟', answerType: 'yes_no_partial', order: 8),
          ChecklistQuestion(id: 'fk_9', text: 'کپسول اطفای حریق متصل به بدنه لیفتراک دارای شارژ معتبر است؟', answerType: 'yes_no_partial', order: 9),
          ChecklistQuestion(id: 'fk_10', text: 'لاستیک‌ها سالم، فاقد ترک‌خوردگی عمیق و دارای عاج مناسبند؟', answerType: 'yes_no_partial', order: 10),
          ChecklistQuestion(id: 'fk_11', text: 'آینه‌های بغل و آینه دید عقب سالم و تنظیم شده‌اند؟', answerType: 'yes_no_partial', order: 11),
        ],
      ),

      // 9. HSE-6-028 - ایمنی برق عمومی
      Checklist(
        id: 'hse_6_028_gen',
        code: 'HSE-6-028-1',
        title: 'ایمنی برق عمومی و تجهیزات',
        category: 'ایمنی برق',
        description: 'بازرسی سیستم‌های الکتریکی عمومی، ارتینگ و کلیدها',
        questions: const [
          ChecklistQuestion(id: 'e_gen_1', text: 'تمامی سیم‌کشی‌ها داخل لوله فولادی، خرطومی استاندارد یا داکت هستند؟', answerType: 'yes_no_partial_na', order: 1),
          ChecklistQuestion(id: 'e_gen_2', text: 'پریزها و کلیدهای روشنایی دارای درپوش سالم، محکم و بدون شکستگی هستند؟', answerType: 'yes_no_partial_na', order: 2),
          ChecklistQuestion(id: 'e_gen_3', text: 'سیستم ارتینگ (اتصال به زمین) سراسری برقرار و دارای چاه ارت استاندارد است؟', answerType: 'yes_no_partial_na', order: 3),
          ChecklistQuestion(id: 'e_gen_4', text: 'مقاومت چاه‌های ارت به صورت دوره‌ای اندازه‌گیری و زیر ۵ اهم است؟', answerType: 'yes_no_partial_na', order: 4),
          ChecklistQuestion(id: 'e_gen_5', text: 'کلیدهای محافظ جان (RCD / ELCB) در مدارهای حساس نصب و تست شده‌اند؟', answerType: 'yes_no_partial_na', order: 5),
          ChecklistQuestion(id: 'e_gen_6', text: 'هیچ‌گونه اضافه بار و تقسیم بار نامتعادل روی خطوط برق وجود ندارد؟', answerType: 'yes_no_partial_na', order: 6),
          ChecklistQuestion(id: 'e_gen_7', text: 'سیم‌های سیار استاندارد، بدون زدگی و جمع‌آوری‌شده پس از اتمام کارند؟', answerType: 'yes_no_partial_na', order: 7),
          ChecklistQuestion(id: 'e_gen_8', text: 'روشنایی اضطراری متصل به UPS یا ژنراتور در زمان قطعی برق فعال می‌شود؟', answerType: 'yes_no_partial_na', order: 8),
          ChecklistQuestion(id: 'e_gen_9', text: 'علائم خطر برق‌گرفتگی در تمام مناطق تأسیسات الکتریکی نصب است؟', answerType: 'yes_no_partial_na', order: 9),
          ChecklistQuestion(id: 'e_gen_10', text: 'پرسنل برق‌کار دارای تجهیزات حفاظت فردی عایق (دستکش، کفش، ابزار عایق ۱۰۰۰ ولت) هستند؟', answerType: 'yes_no_partial_na', order: 10),
          ChecklistQuestion(id: 'e_gen_11', text: 'ترمینال‌ها و اتصالات الکتریکی فاقد داغ‌زدگی و شل‌شدگی هستند؟', answerType: 'yes_no_partial_na', order: 11),
          ChecklistQuestion(id: 'e_gen_12', text: 'فیوزها متناسب با آمپراژ کابل و مصرف‌کننده‌ها انتخاب شده‌اند؟', answerType: 'yes_no_partial_na', order: 12),
          ChecklistQuestion(id: 'e_gen_13', text: 'جعبه تقسیم‌ها دارای درب بسته و عایق‌بندی مناسب رطوبت و گردوغبارند؟', answerType: 'yes_no_partial_na', order: 13),
          ChecklistQuestion(id: 'e_gen_14', text: 'کابل‌های عبوری از کف دارای پل‌های فلزی محافظ جهت جلوگیری از لهیدگی هستند؟', answerType: 'yes_no_partial_na', order: 14),
          ChecklistQuestion(id: 'e_gen_15', text: 'سیستم صاعقه‌گیر ساختمان‌ها و دکل‌ها تست شده و سالم است؟', answerType: 'yes_no_partial_na', order: 15),
          ChecklistQuestion(id: 'e_gen_16', text: 'تابلوهای برق و تجهیزات برقی فاقد هرگونه نشتی آب بالاسری هستند؟', answerType: 'yes_no_partial_na', order: 16),
          ChecklistQuestion(id: 'e_gen_17', text: 'دستورالعمل احیای قلبی ریوی و برق‌گرفتگی در اتاق‌های برق نصب است؟', answerType: 'yes_no_partial_na', order: 17),
          ChecklistQuestion(id: 'e_gen_18', text: 'بازرسی ترموویژن (گرمانگاری) اتصالات برق انجام شده است؟', answerType: 'yes_no_partial_na', order: 18),
        ],
      ),

      // 10. HSE-6-028 - تابلوهای برق اصلی و توزیع
      Checklist(
        id: 'hse_6_028_panel',
        code: 'HSE-6-028-2',
        title: 'بازرسی تابلوهای برق توزیع و قدرت',
        category: 'ایمنی برق',
        description: 'کنترل تابلوهای برق، شینه‌ها، کلیدهای مینیاتوری و قفل ایمنی',
        questions: const [
          ChecklistQuestion(id: 'pnl_1', text: 'درب تابلوهای برق همیشه قفل و کلید آن در اختیار فرد مجاز است؟', answerType: 'yes_no_partial_na', order: 1),
          ChecklistQuestion(id: 'pnl_2', text: 'شیلد و پوشش محافظ پلی‌کربنات روی شینه‌های برق‌دار نصب است؟', answerType: 'yes_no_partial_na', order: 2),
          ChecklistQuestion(id: 'pnl_3', text: 'فرش عایق لاستیکی ۲۰ کیلوولت با استاندارد معتبر جلوی تابلو پهن است؟', answerType: 'yes_no_partial_na', order: 3),
          ChecklistQuestion(id: 'pnl_4', text: 'نقشه تک‌خطی (Single Line Diagram) و راهنمای کلیدها داخل تابلو نصب است؟', answerType: 'yes_no_partial_na', order: 4),
          ChecklistQuestion(id: 'pnl_5', text: 'حریم دسترسی ۱ متری مقابل تابلو کاملاً باز و عاری از هرگونه شیء است؟', answerType: 'yes_no_partial_na', order: 5),
          ChecklistQuestion(id: 'pnl_6', text: 'بدنه فلزی و درب تابلو با تسمه مسی ارت مطمئن شده‌اند؟', answerType: 'yes_no_partial_na', order: 6),
          ChecklistQuestion(id: 'pnl_7', text: 'چراغ‌های سیگنال فازها و ولت‌متر/آمپرمتر روی درب تابلو سالمند؟', answerType: 'yes_no_partial_na', order: 7),
          ChecklistQuestion(id: 'pnl_8', text: 'گلند کابل‌های ورودی و خروجی تابلو محکم و بدون درز باز هستند؟', answerType: 'yes_no_partial_na', order: 8),
          ChecklistQuestion(id: 'pnl_9', text: 'فن و فیلترهای تهویه هوای داخل تابلو تمیز و فعالند؟', answerType: 'yes_no_partial_na', order: 9),
          ChecklistQuestion(id: 'pnl_10', text: 'داخل تابلو فاقد گردوغبار شدید، تارعنکبوت و رطوبت است؟', answerType: 'yes_no_partial_na', order: 10),
          ChecklistQuestion(id: 'pnl_11', text: 'هیچ وسیله متفرقه، کاغذ یا ابزاری داخل تابلو نگهداری نمی‌شود؟', answerType: 'yes_no_partial_na', order: 11),
          ChecklistQuestion(id: 'pnl_12', text: 'سیستم LOTO (قفل و برچسب‌گذاری ایمنی) روی کلیدهای اصلی موجود است؟', answerType: 'yes_no_partial_na', order: 12),
          ChecklistQuestion(id: 'pnl_13', text: 'کپسول اطفای حریق CO2 مناسب در نزدیکی تابلوی برق نصب است؟', answerType: 'yes_no_partial_na', order: 13),
          ChecklistQuestion(id: 'pnl_14', text: 'سیم‌کشی‌های داخل تابلو فرم‌بندی شده و شماره‌سیم (وارنیش) دارند؟', answerType: 'yes_no_partial_na', order: 14),
          ChecklistQuestion(id: 'pnl_15', text: 'کلید اصلی قطع بار (MCCB/ACB) روان و بدون گیر مکانیکی است؟', answerType: 'yes_no_partial_na', order: 15),
          ChecklistQuestion(id: 'pnl_16', text: 'رله‌های حفاظتی، بی‌متال‌ها و کنترل فازها فعال و تنظیم هستند؟', answerType: 'yes_no_partial_na', order: 16),
          ChecklistQuestion(id: 'pnl_17', text: 'علامت هشدار ولتاژ خطرناک و ولتاژ نامی روی درب تابلو درج است؟', answerType: 'yes_no_partial_na', order: 17),
          ChecklistQuestion(id: 'pnl_18', text: 'هیچ قطعه کلید مینیاتوری بدون قاب و محافظ در تابلو وجود ندارد؟', answerType: 'yes_no_partial_na', order: 18),
        ],
      ),

      // 11. HSE-6-028 - پست برق و ترانسفورماتور 20kV
      Checklist(
        id: 'hse_6_028_sub',
        code: 'HSE-6-028-3',
        title: 'بازرسی پست برق و ترانسفورماتورها',
        category: 'ایمنی برق',
        description: 'ایمنی ولتاژ متوسط و بالا (20kV)، ترانس‌ها و دژنکتورها',
        questions: const [
          ChecklistQuestion(id: 'sub_1', text: 'درب پست برق قفل، ورود افراد متفرقه ممنوع و کلید در اختیار مسئول است؟', answerType: 'yes_no_partial_na', order: 1),
          ChecklistQuestion(id: 'sub_2', text: 'ترانسفورماتور فاقد نشتی روغن، صدای غیرعادی (زوزه) و داغی بیش از حد است؟', answerType: 'yes_no_partial_na', order: 2),
          ChecklistQuestion(id: 'sub_3', text: 'گیج روغن، رطوبت‌گیر سیلیکاژل (رنگ آبی) و ترمومتر ترانس سالمند؟', answerType: 'yes_no_partial_na', order: 3),
          ChecklistQuestion(id: 'sub_4', text: 'حوضچه روغن‌گیر زیر ترانس تمیز و دارای شن بادامی بدون زباله است؟', answerType: 'yes_no_partial_na', order: 4),
          ChecklistQuestion(id: 'sub_5', text: 'اهرم و میله عایق نجات پرسنل (چوب استیک ۲۰ کیلوولت) در پست موجود است؟', answerType: 'yes_no_partial_na', order: 5),
          ChecklistQuestion(id: 'sub_6', text: 'دستکش و کفش عایق فشار قوی ۲۰ کیلوولت با تاریخ آزمون معتبر موجود است؟', answerType: 'yes_no_partial_na', order: 6),
          ChecklistQuestion(id: 'sub_7', text: 'فازمتر فشار قوی (اپومتر ۲۰kV) سالم و آماده بکار در پست وجود دارد؟', answerType: 'yes_no_partial_na', order: 7),
          ChecklistQuestion(id: 'sub_8', text: 'اتصال زمین بدنه ترانس و نول ترانس به شبکه ارتینگ مطمئن است؟', answerType: 'yes_no_partial_na', order: 8),
          ChecklistQuestion(id: 'sub_9', text: 'دژنکتورها و سکسیونرهای ۲۰ کیلوولت تست و سرویس دوره‌ای شده‌اند؟', answerType: 'yes_no_partial_na', order: 9),
          ChecklistQuestion(id: 'sub_10', text: 'سیستم اعلام و اطفای حریق اتوماتیک
